# Generated by Django 3.0.8 on 2020-09-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile',
        ),
        migrations.AddField(
            model_name='customuser',
            name='key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
